package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	gitv1 "github.com/gitfrok/backend/gen/proto/git/v1"
	codereviewapi "github.com/gitfrok/backend/modules/codereview/api"
	policyapi "github.com/gitfrok/backend/modules/policy/api"
)

// Protection answers whether an exact ref carries a branch-protection rule, from
// Repository/Git's own tenant-scoped projection of BranchProtectionChanged. It is
// a port so the receive-pack path never calls Code Review and never reads its
// tables (SPEC-0019 AC7).
type Protection interface {
	// ProtectedRefs lists the protected refs in one tenant and repository.
	ProtectedRefs(tenantID, repositoryID string) []string
	// Set installs or replaces one exact-ref rule, delivered by the
	// SetProtection RPC (git.proto) from the process that owns the rules.
	Set(rule codereviewapi.BranchProtection)
}

// protectedRefsEnv carries the refs a push may not update to the pre-receive
// hook. The hook is the last moment a ref update can be refused: by the time
// git-receive-pack has run, the refs have already moved.
const protectedRefsEnv = "GITFROK_REJECTED_REFS"

// preReceiveHook refuses exactly the refs git-storaged listed, and nothing else.
//
// It makes no decision of its own. Every ref it rejects was refused by the PDP
// before git-receive-pack started; the hook is the mechanism, not the policy. It
// is written in POSIX sh because it runs inside git's own hook environment, where
// nothing else is guaranteed to exist.
const preReceiveHook = `#!/bin/sh
# Generated by git-storaged. Do not edit: it is rewritten on every push.
#
# Refuses the refs GITFROK_REJECTED_REFS names. The decision was made by the
# policy decision point before this hook ran (SPEC-0019 AC3).
status=0
while read -r _old _new ref; do
	case ":${GITFROK_REJECTED_REFS}:" in
	*":${ref}:"*)
		printf 'gitfrok: %s is protected; open a merge request\n' "${ref}" >&2
		status=1
		;;
	esac
done
exit "${status}"
`

// installPreReceiveHook writes the hook into the bare repository. It is rewritten
// on every push rather than assumed present, so a repository restored from a
// backup, created by an import, or edited by hand cannot end up accepting a
// direct push to a protected ref because its hook went missing.
func installPreReceiveHook(repositoryPath string) error {
	hooks := filepath.Join(repositoryPath, "hooks")
	if err := os.MkdirAll(hooks, 0o750); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(hooks, "pre-receive"), []byte(preReceiveHook), 0o700)
}

// rejectedRefs is the set of refs this push may not update.
//
// Protection comes from the local projection; the refusal comes from the PDP. For
// each protected ref, storage asks whether this principal may write it as a
// direct push, with `protected` and `operation` derived here rather than supplied
// by anyone. A ref whose decision is anything but a clear allow is rejected, so a
// PDP that is unreachable closes the branch rather than opening it.
func (s *Server) rejectedRefs(ctx context.Context, op *gitv1.OperationContext) []string {
	if s.protection == nil {
		return nil
	}
	protected := s.protection.ProtectedRefs(op.GetTenantId(), op.GetRepositoryId())
	if len(protected) == 0 {
		return nil
	}

	rejected := make([]string, 0, len(protected))
	for _, ref := range protected {
		decision, err := s.pdp.Decide(ctx, policyapi.Request{
			TenantID: op.GetTenantId(),
			Subject: policyapi.Subject{
				ID: op.GetActorId(), TenantID: op.GetTenantId(),
				Roles: append([]string(nil), op.GetActorRoles()...),
			},
			Action:   "repo.write",
			Resource: policyapi.Resource{Type: "repository", ID: op.GetRepositoryId()},
			Context: map[string]string{
				"request_id": op.GetRequestId(),
				"operation":  "direct_push",
				"target_ref": ref,
				"protected":  "true",
			},
		})
		if err != nil || !decision.Allowed {
			rejected = append(rejected, ref)
		}
	}
	sort.Strings(rejected)
	return rejected
}

// hookEnvironment adds the rejected refs to the environment git-receive-pack
// passes down to the hook, preserving whatever the caller had already set. It
// carries nothing else about the decision — no roles, no decision ID, no policy
// reason, none of which a hook has any use for.
func hookEnvironment(existing []string, rejected []string) []string {
	if existing == nil {
		existing = os.Environ()
	}
	return append(existing, fmt.Sprintf("%s=%s", protectedRefsEnv, strings.Join(rejected, ":")))
}
