// Package custody is the Agent context's production key-custody adapter (T-0040,
// SPEC-0044 AC1/AC2, ADR-0064, ADR-0066): the CA signs through a custody-held,
// non-exportable ECDSA P-256 key and holds a key REFERENCE, never key material.
//
// The seam is Signer: generate-by-reference, read-the-public-half, sign-a-digest —
// the narrow sign-through interface ADR-0064 decision 2 drew, deliberately narrow
// enough that a future general platform-secrets ADR can absorb it without
// reopening the posture (ADR-0066 decision 3). Nothing wider belongs here: no
// decrypt, no wrap/unwrap, no secret read — the agent CA is a signing authority
// and custody serves it nothing else. PKI-engine delegation is NOT this seam
// (ADR-0066 decision 1): issuance, serials and revocation stay control-plane
// acts, and transit merely signs.
//
// Two Signer implementations live here:
//
//   - OpenBao — the production provider (ADR-0066 decision 1): OpenBao's transit
//     engine over its HTTP API, Kubernetes auth, no static credential.
//   - FakeSigner — the CI custody service: the same interface over in-memory
//     ECDSA keys, so unit and CI suites never touch the production provider
//     (SPEC-0044 Test plan). It is test custody in the same sense pki.DevCA is —
//     the composition root must never reach it in production.
//
// On top of the seam sit the two control-plane roles SPEC-0044 names:
//
//   - Issuer implements api.CertificateIssuer as a drop-in peer of pki.DevCA —
//     the composition-root swap is a wiring change, not an issuance-logic change
//     (ADR-0066 context).
//   - Bundle is the staged CA trust bundle with the dual-validate rotation
//     window (AC2): stage a new root beside the old, both validate during the
//     overlap, new issuance chains to the new key, and the old root leaves only
//     after every certificate it issued predates its removal.
//
// DEFERRED — reconcile distribution of the bundle: on 2026-08-15 the agent/v1
// DesiredState message (governance/contracts/proto/agent/v1/agent.proto) carries
// only a generation counter and per-component signed release refs — NO field
// capable of staging a CA trust bundle (multiple roots / bundle revision). Per
// SPEC-0044's Contracts-touched rule, an additive agent/v1 field under its own
// governance PR must come first; until it lands, Bundle's state moves nowhere
// but in-process, and its Snapshot/Restore surface is where the reconcile
// wiring attaches. The window LOGIC tests here exercise that in-memory staging
// abstraction; none of them stands in for distribution.
package custody

import (
	"context"
	"crypto/ecdsa"
	"errors"
)

// KeyRef names a signing key the custody service holds: its name/path inside
// the provider (the transit key name for OpenBao). It is the ONLY form in
// which the CA ever knows its signing key (ADR-0064 decision 2). A KeyRef
// carries no material and grants nothing by itself — the custody service's
// auth and policy decide what it may sign.
type KeyRef string

// String returns the reference itself; KeyRef is never formatted anywhere
// else — there is no secret in it to leak, and no method of this package
// formats material it does not have.
func (r KeyRef) String() string { return string(r) }

// Signer is the narrow custody seam (ADR-0064 decision 2). Every method is a
// reference-in operation: the caller names a key, the custody service acts on
// the key it holds, and at most PUBLIC material or a SIGNATURE comes back.
// No method returns, or can be composed to recover, private key material.
type Signer interface {
	// GenerateKey creates one non-exportable ECDSA P-256 signing key inside
	// the custody service and returns ONLY its reference. The private key is
	// generated by the provider, inside its barrier, and never leaves it.
	GenerateKey(ctx context.Context, name string) (KeyRef, error)
	// PublicKey returns the public half of the referenced key. Public
	// material is not secret; it is what the control plane embeds in the CA
	// certificate it self-signs through the key.
	PublicKey(ctx context.Context, ref KeyRef) (*ecdsa.PublicKey, error)
	// SignDigest signs one SHA-256 digest with the referenced key and returns
	// the ASN.1 DER ECDSA signature. The digest form is what x509 certificate
	// signing needs: the TBS structure is hashed once, here, and the provider
	// never sees more than the digest of what it signs.
	SignDigest(ctx context.Context, ref KeyRef, digest []byte) ([]byte, error)
}

// ErrUnavailable reports that the custody service refused or could not be
// reached: a sealed provider, a transport failure, a server error. Losing
// custody is an AVAILABILITY event, never an integrity event (ADR-0066
// decision 6, SPEC-0044 assumption): issuance stops, already-issued
// certificates stay valid until expiry.
var ErrUnavailable = errors.New("custody: signer unavailable")

// ErrNoKey reports that the referenced key does not exist in the custody
// service.
var ErrNoKey = errors.New("custody: no such key")

// ErrKeyExists reports that a key by this name already exists in the custody
// service. Rotation stages a NEW key; staging onto an existing name is the
// kind of mistake this refuses loudly.
var ErrKeyExists = errors.New("custody: key already exists")

// ErrNotECDSAP256 reports a custody key whose type is not the non-exportable
// ECDSA P-256 this posture fixes (ADR-0066 decision 1). The CA refuses to
// sign through anything else rather than quietly widening the key policy.
var ErrNotECDSAP256 = errors.New("custody: key is not non-exportable ECDSA P-256")
